name: Android

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release
  QT_VERSION: "6.11.0"
  QT_ARCH: "android_arm64_v8a"
  QT_TARGET: "android"
  # https://doc.qt.io/qt-6/android.html
  PLATFORM_VERSION: "36"
  BUILD_TOOLS_VERSION: "36.0.0"
  NDK_VERSION: "27.2.12479018"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: "platform-tools platforms;android-${{env.PLATFORM_VERSION}} build-tools;${{env.BUILD_TOOLS_VERSION}} ndk;${{env.NDK_VERSION}}"

      - name: Install Qt (host)
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          version: ${{env.QT_VERSION}}
          arch: "linux_gcc_64"

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          cache: true
          version: ${{env.QT_VERSION}}
          arch: ${{env.QT_ARCH}}
          target: ${{env.QT_TARGET}}

      - name: Clean up unused files
        working-directory: ${{runner.workspace}}/Qt/${{env.QT_VERSION}}/${{env.QT_ARCH}}
        run: |
          find lib -name 'libQt6Gui*.so' -exec rm {} \;
          find lib -name 'libQt6Network*.so' -exec rm {} \;
          find lib -iname '*FluentWinUI3Style*.cmake' -exec rm {} \;
          find lib -iname '*FusionStyle*.cmake' -exec rm {} \;
          find lib -iname '*ImagineStyle*.cmake' -exec rm {} \;
          find lib -iname '*UniversalStyle*.cmake' -exec rm {} \;
          find qml -name 'libqml_*_FluentWinUI3_*.so' -exec rm {} \;
          find qml -name 'libqml_*_Fusion_*.so' -exec rm {} \;
          find qml -name 'libqml_*_Imagine_*.so' -exec rm {} \;
          find qml -name 'libqml_*_Universal_*.so' -exec rm {} \;

      - name: Configure CMake
        env:
          QT_HOST_PATH: ${{runner.workspace}}/Qt/${{env.QT_VERSION}}/gcc_64
          ANDROID_NDK_ROOT: /usr/local/lib/android/sdk/ndk/${{env.NDK_VERSION}}
        run: ${{runner.workspace}}/Qt/$QT_VERSION/$QT_ARCH/bin/qt-cmake -S . -B build -D CMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        run: cmake --build build --config $BUILD_TYPE

      - name: Prepare signing
        run: echo "${{secrets.KEYSTORE_FILE}}" | base64 -d > "release.jks"

      - name: Package
        run: androiddeployqt --input "build/android-mizu-deployment-settings.json" --output "build/android-build" --release --sign "release.jks" "mizu" --storepass "${{secrets.KEYSTORE_PASSWORD}}" --verbose

      - name: Upload Artifact
        uses: actions/upload-artifact@v7
        with:
          name: mizu-android-arm64-v8a
          archive: false
          path: build/android-build/**/*-signed.apk